exclude_paths:
  - tmp
  - vendor

detectors:
  ControlParameter:
    exclude:
      - Containable::Register#call
  LongParameterList:
    enabled: false
  TooManyMethods:
    exclude:
      - Containable::Builder
  TooManyStatements:
    exclude:
      - Containable::Builder#initialize
      - Containable::Register#call
